name: Test Memory on JPG Files

on:
  push:
    branches:
      - develop

jobs:

  test-memory:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: test de chaque fichier
        run: |
          for file in html/data/*.jpg; do
            file "$file"
          done
