name: Test Memory on JPG Files

on:
  push:
    branches:
      - develop

jobs:

  test-memory:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: test de chaque fichier
        run: |
          for file in html/data/*.jpg; do
            file "$file"
          done

  build-memory:
    runs-on: self-hosted
    needs: test-memory
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build du docker
        run: sudo docker build -t ${{ secrets.DOCKER_USER }}/memory:latest .

  push-memory:
    runs-on: self-hosted
    needs: build-memory
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in vers dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Push l'image vers le hub
        run: sudo docker push ${{ secrets.DOCKER_USER }}/memory:latest

  deploy-memory:
    runs-on: self-hosted
    needs: push-memory
    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: creation du serveur
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no thib@127.0.0.1 << EOF
            #sudo docker pull ${{ secrets.DOCKER_USER }}/memory:latest
            cd ~/memory
            docker-compose down
            docker-compose pull
            docker-compose up -d
          EOF
